"""Strip volatile Jupyter notebook state before committing.

Notebook outputs, execution counts, widget state and local kernel metadata create
large diffs and frequent merge conflicts. This script keeps the source cells and
stable tags, but removes state that should be regenerated by executing the
notebook.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

NOTEBOOK_METADATA_DROP = {
    "kernelspec",
    "language_info",
    "widgets",
    "toc",
    "varInspector",
    "vscode",
    "colab",
}

CELL_METADATA_DROP = {
    "collapsed",
    "execution",
    "ExecuteTime",
    "scrolled",
    "trusted",
}


def clean_notebook(path: Path) -> bool:
    before = path.read_text(encoding="utf-8")
    notebook = json.loads(before)

    metadata = notebook.setdefault("metadata", {})
    for key in NOTEBOOK_METADATA_DROP:
        metadata.pop(key, None)

    for cell in notebook.get("cells", []):
        cell_metadata = cell.setdefault("metadata", {})
        for key in CELL_METADATA_DROP:
            cell_metadata.pop(key, None)

        if cell.get("cell_type") == "code":
            cell["execution_count"] = None
            cell["outputs"] = []

    after = json.dumps(notebook, ensure_ascii=False, indent=1) + "\n"
    if after != before:
        path.write_text(after, encoding="utf-8")
        return True
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        default=[Path("notebooks")],
        help="Notebook files or directories to clean.",
    )
    args = parser.parse_args()

    notebooks: list[Path] = []
    for path in args.paths:
        if path.is_dir():
            notebooks.extend(sorted(path.rglob("*.ipynb")))
        elif path.suffix == ".ipynb":
            notebooks.append(path)

    changed = [path for path in notebooks if clean_notebook(path)]
    for path in changed:
        print(f"cleaned {path}")
    print(f"checked {len(notebooks)} notebook(s), changed {len(changed)}")


if __name__ == "__main__":
    main()
